"""initial semester ops schema

Revision ID: 0909dbebe6f1
Revises:
Create Date: 2026-07-28 14:03:00.924955
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import semester_ops.db.models

revision: str = "0909dbebe6f1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("data_json", sa.JSON(), nullable=False),
        sa.Column("occurred_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_entity", "audit_events", ["entity_type", "entity_id", "occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "external_source_states",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "connector",
            sa.Enum("google", "blackboard", name="sync_connector", native_enum=False),
            nullable=False,
        ),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("sync_token", sa.Text(), nullable=True),
        sa.Column("etag", sa.String(length=500), nullable=True),
        sa.Column("last_modified", sa.String(length=500), nullable=True),
        sa.Column("last_attempt_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("last_success_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connector", "source_key", name="uq_external_source"),
    )
    op.create_table(
        "semesters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.CheckConstraint("end_date >= start_date", name="ck_semester_bounds"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_semesters_is_active"), "semesters", ["is_active"], unique=False)
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "connector",
            sa.Enum("google", "blackboard", name="sync_connector", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "running", "succeeded", "partial", "failed", name="sync_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("started_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("finished_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("created_count", sa.Integer(), nullable=False),
        sa.Column("updated_count", sa.Integer(), nullable=False),
        sa.Column("deleted_count", sa.Integer(), nullable=False),
        sa.Column("conflict_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active_semester_id", sa.String(length=36), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("operational_day_boundary", sa.Time(), nullable=False),
        sa.Column("missed_grace_minutes", sa.Integer(), nullable=False),
        sa.Column("weight_unit", sa.String(length=10), nullable=False),
        sa.Column("calorie_target", sa.Integer(), nullable=True),
        sa.Column("protein_target_grams", sa.Integer(), nullable=True),
        sa.Column("blackboard_ics_url", sa.Text(), nullable=True),
        sa.Column("google_calendar_id", sa.String(length=500), nullable=True),
        sa.Column("schedule_revision", sa.Integer(), nullable=False),
        sa.Column("created_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.CheckConstraint("id = 1", name="ck_singleton_app_settings"),
        sa.CheckConstraint("missed_grace_minutes >= 0", name="ck_missed_grace"),
        sa.ForeignKeyConstraint(["active_semester_id"], ["semesters.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "block_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("semester_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "wake",
                "sleep",
                "commute",
                "class",
                "work",
                "study",
                "meal",
                "workout",
                "chore",
                "appointment",
                "free_time",
                "custom",
                name="block_category",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "flexibility",
            sa.Enum("fixed", "flexible", "optional", name="block_flexibility", native_enum=False),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("weekdays", sa.JSON(), nullable=False),
        sa.Column("local_start_time", sa.Time(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("effective_start_date", sa.Date(), nullable=False),
        sa.Column("effective_end_date", sa.Date(), nullable=False),
        sa.Column("excluded_dates", sa.JSON(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("earliest_start_time", sa.Time(), nullable=True),
        sa.Column("latest_end_time", sa.Time(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("preferred_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("minimum_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("may_split", sa.Boolean(), nullable=False),
        sa.Column("requires_completion", sa.Boolean(), nullable=False),
        sa.Column("calendar_projection", sa.Boolean(), nullable=False),
        sa.Column("managed_dataset", sa.String(length=100), nullable=True),
        sa.Column("source_key", sa.String(length=300), nullable=True),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("cancelled_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("created_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.CheckConstraint("duration_minutes > 0", name="ck_template_duration"),
        sa.CheckConstraint("effective_end_date >= effective_start_date", name="ck_template_bounds"),
        sa.CheckConstraint("priority >= 0 AND priority <= 100", name="ck_template_priority"),
        sa.ForeignKeyConstraint(["semester_id"], ["semesters.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "semester_id", "managed_dataset", "source_key", name="uq_template_source"
        ),
    )
    op.create_index(
        op.f("ix_block_templates_managed_dataset"),
        "block_templates",
        ["managed_dataset"],
        unique=False,
    )
    op.create_index(
        op.f("ix_block_templates_semester_id"), "block_templates", ["semester_id"], unique=False
    )
    op.create_table(
        "courses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("semester_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=True),
        sa.Column("external_source", sa.String(length=100), nullable=False),
        sa.Column("external_id", sa.String(length=500), nullable=True),
        sa.Column("created_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["semester_id"], ["semesters.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "semester_id", "external_source", "external_id", name="uq_course_source"
        ),
    )
    op.create_index(op.f("ix_courses_semester_id"), "courses", ["semester_id"], unique=False)
    op.create_table(
        "import_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("replace_scope", "patch", name="import_mode", native_enum=False),
            nullable=False,
        ),
        sa.Column("managed_dataset", sa.String(length=100), nullable=False),
        sa.Column("semester_id", sa.String(length=36), nullable=True),
        sa.Column("scope_start_date", sa.Date(), nullable=False),
        sa.Column("scope_end_date", sa.Date(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("source_filename", sa.String(length=500), nullable=True),
        sa.Column("source_media_type", sa.String(length=200), nullable=True),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("assumptions", sa.JSON(), nullable=False),
        sa.Column("base_revision", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ready", "blocked", "applied", "rejected", name="draft_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("warnings_accepted", sa.Boolean(), nullable=False),
        sa.Column("created_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("applied_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("rejected_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["semester_id"], ["semesters.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_drafts_idempotency_key"), "import_drafts", ["idempotency_key"], unique=True
    )
    op.create_index(
        op.f("ix_import_drafts_managed_dataset"), "import_drafts", ["managed_dataset"], unique=False
    )
    op.create_index(
        op.f("ix_import_drafts_semester_id"), "import_drafts", ["semester_id"], unique=False
    )
    op.create_table(
        "assignments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("course_id", sa.String(length=36), nullable=True),
        sa.Column("external_source", sa.String(length=100), nullable=False),
        sa.Column("external_uid", sa.String(length=500), nullable=False),
        sa.Column("recurrence_id", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "due_precision",
            sa.Enum("date", "datetime", name="due_precision", native_enum=False),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("due_at_utc", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column(
            "source_state",
            sa.Enum("active", "stale", "canceled", name="external_record_state", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "inbox_status",
            sa.Enum(
                "inbox",
                "planned",
                "completed",
                "ignored",
                "stale",
                "canceled",
                name="assignment_inbox_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("estimated_effort_minutes", sa.Integer(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=True),
        sa.Column("source_dtstamp", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("source_last_modified", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("last_seen_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("created_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "(due_precision = 'date' AND due_date IS NOT NULL) OR (due_precision = 'datetime' AND due_at_utc IS NOT NULL)",
            name="ck_assignment_due_value",
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "external_source", "external_uid", "recurrence_id", name="uq_assignment_source"
        ),
    )
    op.create_index(op.f("ix_assignments_course_id"), "assignments", ["course_id"], unique=False)
    op.create_table(
        "block_occurrences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("semester_id", sa.String(length=36), nullable=False),
        sa.Column("template_id", sa.String(length=36), nullable=True),
        sa.Column("occurrence_date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "wake",
                "sleep",
                "commute",
                "class",
                "work",
                "study",
                "meal",
                "workout",
                "chore",
                "appointment",
                "free_time",
                "custom",
                name="block_category",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "flexibility",
            sa.Enum("fixed", "flexible", "optional", name="block_flexibility", native_enum=False),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("planned_start_utc", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("planned_end_utc", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("actual_start_utc", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("actual_end_utc", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "in_progress",
                "completed",
                "skipped",
                "missed",
                name="tracking_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_override", sa.Boolean(), nullable=False),
        sa.Column("override_reason", sa.String(length=500), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("preferred_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("minimum_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("earliest_start_utc", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("latest_end_utc", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("may_split", sa.Boolean(), nullable=False),
        sa.Column("requires_completion", sa.Boolean(), nullable=False),
        sa.Column("calendar_projection", sa.Boolean(), nullable=False),
        sa.Column("managed_dataset", sa.String(length=100), nullable=True),
        sa.Column("source_key", sa.String(length=300), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("cancelled_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("created_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.CheckConstraint("status != 'missed'", name="ck_occurrence_missed_is_derived"),
        sa.CheckConstraint(
            "actual_end_utc IS NULL OR actual_start_utc IS NULL OR actual_end_utc >= actual_start_utc",
            name="ck_occurrence_actual_range",
        ),
        sa.CheckConstraint(
            "planned_end_utc > planned_start_utc", name="ck_occurrence_planned_range"
        ),
        sa.CheckConstraint("priority >= 0 AND priority <= 100", name="ck_occurrence_priority"),
        sa.ForeignKeyConstraint(["semester_id"], ["semesters.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["template_id"], ["block_templates.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "semester_id", "managed_dataset", "source_key", name="uq_occurrence_source"
        ),
        sa.UniqueConstraint("template_id", "occurrence_date", name="uq_template_occurrence_date"),
    )
    op.create_index(
        op.f("ix_block_occurrences_cancelled_at"),
        "block_occurrences",
        ["cancelled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_block_occurrences_managed_dataset"),
        "block_occurrences",
        ["managed_dataset"],
        unique=False,
    )
    op.create_index(
        op.f("ix_block_occurrences_occurrence_date"),
        "block_occurrences",
        ["occurrence_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_block_occurrences_planned_end_utc"),
        "block_occurrences",
        ["planned_end_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_block_occurrences_planned_start_utc"),
        "block_occurrences",
        ["planned_start_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_block_occurrences_semester_id"), "block_occurrences", ["semester_id"], unique=False
    )
    op.create_index(
        op.f("ix_block_occurrences_template_id"), "block_occurrences", ["template_id"], unique=False
    )
    op.create_index(
        "ix_occurrences_schedule",
        "block_occurrences",
        ["semester_id", "planned_start_utc", "planned_end_utc"],
        unique=False,
    )
    op.create_table(
        "import_changes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("draft_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "operation",
            sa.Enum("add", "update", "cancel", name="change_operation", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "entity_type",
            sa.Enum(
                "semester", "template", "occurrence", name="import_entity_type", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("applied_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["draft_id"], ["import_drafts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_changes_draft_id"), "import_changes", ["draft_id"], unique=False
    )
    op.create_index(
        op.f("ix_import_changes_target_id"), "import_changes", ["target_id"], unique=False
    )
    op.create_table(
        "import_issues",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("draft_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("info", "warning", "error", name="issue_severity", native_enum=False),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=True),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["draft_id"], ["import_drafts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_import_issues_draft_id"), "import_issues", ["draft_id"], unique=False)
    op.create_table(
        "assignment_block_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("assignment_id", sa.String(length=36), nullable=False),
        sa.Column("occurrence_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["assignment_id"], ["assignments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["occurrence_id"], ["block_occurrences.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assignment_id", "occurrence_id", name="uq_assignment_block_link"),
    )
    op.create_index(
        op.f("ix_assignment_block_links_assignment_id"),
        "assignment_block_links",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignment_block_links_occurrence_id"),
        "assignment_block_links",
        ["occurrence_id"],
        unique=False,
    )
    op.create_table(
        "calendar_event_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("occurrence_id", sa.String(length=36), nullable=False),
        sa.Column("calendar_id", sa.String(length=500), nullable=False),
        sa.Column("event_id", sa.String(length=200), nullable=False),
        sa.Column("etag", sa.String(length=500), nullable=True),
        sa.Column("last_synced_local_revision", sa.Integer(), nullable=False),
        sa.Column("last_synced_start_utc", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("last_synced_end_utc", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("remote_updated_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("last_synced_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["occurrence_id"], ["block_occurrences.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("calendar_id", "event_id", name="uq_calendar_event"),
    )
    op.create_index(
        op.f("ix_calendar_event_links_occurrence_id"),
        "calendar_event_links",
        ["occurrence_id"],
        unique=True,
    )
    op.create_table(
        "checklist_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("occurrence_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("completed_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("skipped_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["occurrence_id"], ["block_occurrences.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checklist_items_occurrence_id"), "checklist_items", ["occurrence_id"], unique=False
    )
    op.create_table(
        "meal_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("occurrence_id", sa.String(length=36), nullable=False),
        sa.Column("food_name", sa.String(length=300), nullable=False),
        sa.Column("unit", sa.String(length=100), nullable=False),
        sa.Column("planned_quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("consumed_quantity", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("calories_per_unit", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("protein_grams_per_unit", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("completed_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.CheckConstraint("calories_per_unit >= 0", name="ck_meal_calories"),
        sa.CheckConstraint(
            "consumed_quantity IS NULL OR consumed_quantity >= 0", name="ck_meal_consumed_quantity"
        ),
        sa.CheckConstraint("planned_quantity > 0", name="ck_meal_planned_quantity"),
        sa.CheckConstraint("protein_grams_per_unit >= 0", name="ck_meal_protein"),
        sa.ForeignKeyConstraint(["occurrence_id"], ["block_occurrences.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_meal_items_occurrence_id"), "meal_items", ["occurrence_id"], unique=False
    )
    op.create_table(
        "sync_conflicts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sync_run_id", sa.String(length=36), nullable=False),
        sa.Column("occurrence_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open", "keep_planner", "use_remote", name="sync_conflict_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("planner_start_utc", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("planner_end_utc", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("remote_start_utc", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("remote_end_utc", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("base_start_utc", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("base_end_utc", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.Column("created_at", semester_ops.db.models.UTCDateTime(), nullable=False),
        sa.Column("resolved_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["occurrence_id"], ["block_occurrences.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sync_run_id"], ["sync_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sync_conflicts_occurrence_id"), "sync_conflicts", ["occurrence_id"], unique=False
    )
    op.create_table(
        "workout_exercises",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("occurrence_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("planned_sets", sa.Integer(), nullable=False),
        sa.Column("rep_min", sa.Integer(), nullable=True),
        sa.Column("rep_max", sa.Integer(), nullable=True),
        sa.Column("target_weight", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("weight_unit", sa.String(length=10), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("planned_sets > 0", name="ck_exercise_planned_sets"),
        sa.CheckConstraint("rep_max IS NULL OR rep_max >= rep_min", name="ck_exercise_rep_max"),
        sa.CheckConstraint("rep_min IS NULL OR rep_min >= 0", name="ck_exercise_rep_min"),
        sa.CheckConstraint(
            "target_weight IS NULL OR target_weight >= 0", name="ck_exercise_target_weight"
        ),
        sa.ForeignKeyConstraint(["occurrence_id"], ["block_occurrences.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workout_exercises_occurrence_id"),
        "workout_exercises",
        ["occurrence_id"],
        unique=False,
    )
    op.create_table(
        "workout_sets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("exercise_id", sa.String(length=36), nullable=False),
        sa.Column("set_number", sa.Integer(), nullable=False),
        sa.Column("target_reps", sa.Integer(), nullable=True),
        sa.Column("actual_reps", sa.Integer(), nullable=True),
        sa.Column("actual_weight", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("completed_at", semester_ops.db.models.UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "actual_reps IS NULL OR actual_reps >= 0", name="ck_workout_actual_reps"
        ),
        sa.CheckConstraint(
            "actual_weight IS NULL OR actual_weight >= 0", name="ck_workout_actual_weight"
        ),
        sa.CheckConstraint("set_number > 0", name="ck_workout_set_number"),
        sa.ForeignKeyConstraint(["exercise_id"], ["workout_exercises.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exercise_id", "set_number", name="uq_exercise_set_number"),
    )
    op.create_index(
        op.f("ix_workout_sets_exercise_id"), "workout_sets", ["exercise_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workout_sets_exercise_id"), table_name="workout_sets")
    op.drop_table("workout_sets")
    op.drop_index(op.f("ix_workout_exercises_occurrence_id"), table_name="workout_exercises")
    op.drop_table("workout_exercises")
    op.drop_index(op.f("ix_sync_conflicts_occurrence_id"), table_name="sync_conflicts")
    op.drop_table("sync_conflicts")
    op.drop_index(op.f("ix_meal_items_occurrence_id"), table_name="meal_items")
    op.drop_table("meal_items")
    op.drop_index(op.f("ix_checklist_items_occurrence_id"), table_name="checklist_items")
    op.drop_table("checklist_items")
    op.drop_index(op.f("ix_calendar_event_links_occurrence_id"), table_name="calendar_event_links")
    op.drop_table("calendar_event_links")
    op.drop_index(
        op.f("ix_assignment_block_links_occurrence_id"), table_name="assignment_block_links"
    )
    op.drop_index(
        op.f("ix_assignment_block_links_assignment_id"), table_name="assignment_block_links"
    )
    op.drop_table("assignment_block_links")
    op.drop_index(op.f("ix_import_issues_draft_id"), table_name="import_issues")
    op.drop_table("import_issues")
    op.drop_index(op.f("ix_import_changes_target_id"), table_name="import_changes")
    op.drop_index(op.f("ix_import_changes_draft_id"), table_name="import_changes")
    op.drop_table("import_changes")
    op.drop_index("ix_occurrences_schedule", table_name="block_occurrences")
    op.drop_index(op.f("ix_block_occurrences_template_id"), table_name="block_occurrences")
    op.drop_index(op.f("ix_block_occurrences_semester_id"), table_name="block_occurrences")
    op.drop_index(op.f("ix_block_occurrences_planned_start_utc"), table_name="block_occurrences")
    op.drop_index(op.f("ix_block_occurrences_planned_end_utc"), table_name="block_occurrences")
    op.drop_index(op.f("ix_block_occurrences_occurrence_date"), table_name="block_occurrences")
    op.drop_index(op.f("ix_block_occurrences_managed_dataset"), table_name="block_occurrences")
    op.drop_index(op.f("ix_block_occurrences_cancelled_at"), table_name="block_occurrences")
    op.drop_table("block_occurrences")
    op.drop_index(op.f("ix_assignments_course_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index(op.f("ix_import_drafts_semester_id"), table_name="import_drafts")
    op.drop_index(op.f("ix_import_drafts_managed_dataset"), table_name="import_drafts")
    op.drop_index(op.f("ix_import_drafts_idempotency_key"), table_name="import_drafts")
    op.drop_table("import_drafts")
    op.drop_index(op.f("ix_courses_semester_id"), table_name="courses")
    op.drop_table("courses")
    op.drop_index(op.f("ix_block_templates_semester_id"), table_name="block_templates")
    op.drop_index(op.f("ix_block_templates_managed_dataset"), table_name="block_templates")
    op.drop_table("block_templates")
    op.drop_table("app_settings")
    op.drop_table("sync_runs")
    op.drop_index(op.f("ix_semesters_is_active"), table_name="semesters")
    op.drop_table("semesters")
    op.drop_table("external_source_states")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index("ix_audit_entity", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
