import { addDays, set, startOfDay } from "date-fns";

import type { LifeItem } from "@/lib/life-os/types";

function at(baseDate: Date, dayOffset: number, hour: number, minute = 0) {
  return set(addDays(baseDate, dayOffset), {
    hours: hour,
    minutes: minute,
    seconds: 0,
    milliseconds: 0,
  }).toISOString();
}

export function buildSeedLifeItems(referenceDate = new Date()): LifeItem[] {
  const baseDate = startOfDay(referenceDate);

  return [
    {
      id: "lease-renewal-packet",
      type: "task",
      title: "Submit lease renewal packet",
      notes: "Upload signed form and proof of renter's insurance.",
      status: "todo",
      priority: "critical",
      dueAt: at(baseDate, 0, 10, 0),
      category: "Home admin",
      tags: ["paperwork", "home"],
      estimatedMinutes: 35,
      energy: "medium",
    },
    {
      id: "electric-bill",
      type: "bill",
      title: "Pay electric bill",
      notes: "Autopay lapsed after the new card arrived.",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, -3, 18, 0),
      category: "Utilities",
      tags: ["monthly", "essential"],
      amount: 86,
      estimatedMinutes: 10,
      energy: "low",
      recurring: true,
    },
    {
      id: "internet-bill",
      type: "bill",
      title: "Pay internet bill",
      notes: "Bundle discount expires this month.",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, -1, 17, 30),
      category: "Utilities",
      tags: ["monthly", "home"],
      amount: 58,
      estimatedMinutes: 8,
      energy: "low",
      recurring: true,
    },
    {
      id: "water-garden",
      type: "reminder",
      title: "Water the herb garden",
      notes: "The rosemary is happiest before noon.",
      status: "todo",
      priority: "low",
      dueAt: at(baseDate, 0, 8, 30),
      category: "Home",
      tags: ["routine", "quick win"],
      estimatedMinutes: 10,
      energy: "low",
      recurring: true,
    },
    {
      id: "pick-up-prescription",
      type: "errand",
      title: "Pick up prescription refill",
      notes: "Bring the updated insurance card to the counter.",
      status: "scheduled",
      priority: "medium",
      dueAt: at(baseDate, 0, 13, 45),
      scheduledAt: at(baseDate, 0, 13, 45),
      category: "Health",
      tags: ["drive", "today"],
      location: "Lakeview Pharmacy",
      estimatedMinutes: 25,
      energy: "medium",
    },
    {
      id: "therapy-session",
      type: "appointment",
      title: "Therapy session",
      notes: "Bring notes from the burnout journal.",
      status: "scheduled",
      priority: "high",
      scheduledAt: at(baseDate, 0, 15, 0),
      category: "Wellbeing",
      tags: ["appointment", "mental health"],
      location: "North Loop Clinic",
      estimatedMinutes: 60,
      energy: "medium",
    },
    {
      id: "school-forms",
      type: "task",
      title: "Finalize school forms",
      notes: "Doctor signature already uploaded; just review emergency contacts.",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, 0, 18, 0),
      category: "Family",
      tags: ["deadline", "admin"],
      estimatedMinutes: 50,
      energy: "medium",
    },
    {
      id: "budget-review",
      type: "task",
      title: "Finish quarterly budget review",
      notes: "Flag anything above the dining-out cap before Friday.",
      status: "in_progress",
      priority: "critical",
      dueAt: at(baseDate, 1, 11, 0),
      category: "Finance",
      tags: ["planning", "important"],
      estimatedMinutes: 90,
      energy: "high",
    },
    {
      id: "tax-folder",
      type: "task",
      title: "Prepare tax folder for accountant",
      notes: "Receipts are already in the inbox stack; combine them into one PDF.",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, 2, 16, 0),
      category: "Finance",
      tags: ["paperwork", "finance"],
      estimatedMinutes: 120,
      energy: "high",
    },
    {
      id: "dental-cleaning",
      type: "appointment",
      title: "Dental cleaning",
      notes: "Leave 15 minutes early for parking by the river lot.",
      status: "scheduled",
      priority: "medium",
      scheduledAt: at(baseDate, 1, 9, 0),
      category: "Health",
      tags: ["appointment"],
      location: "Riverfront Dental",
      estimatedMinutes: 55,
      energy: "medium",
    },
    {
      id: "parking-permit",
      type: "bill",
      title: "Pay parking permit renewal",
      notes: "The old permit expires on Sunday morning.",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 2, 12, 0),
      category: "Auto",
      tags: ["civic", "deadline"],
      amount: 120,
      estimatedMinutes: 15,
      energy: "low",
    },
    {
      id: "donation-drop",
      type: "errand",
      title: "Drop donation bags",
      notes: "Back seat is already loaded.",
      status: "todo",
      priority: "low",
      dueAt: at(baseDate, 1, 17, 0),
      category: "Home",
      tags: ["declutter"],
      location: "Oak Street Donation Center",
      estimatedMinutes: 30,
      energy: "medium",
    },
    {
      id: "text-mom",
      type: "reminder",
      title: "Text Mom about Sunday brunch",
      status: "scheduled",
      priority: "low",
      scheduledAt: at(baseDate, 1, 18, 30),
      category: "Relationships",
      tags: ["family", "quick win"],
      estimatedMinutes: 5,
      energy: "low",
    },
    {
      id: "summer-camp",
      type: "task",
      title: "Book summer camp week",
      notes: "Popular weeks are already showing waitlists.",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, 4, 14, 0),
      category: "Family",
      tags: ["registration", "future planning"],
      estimatedMinutes: 45,
      energy: "medium",
    },
    {
      id: "receipts",
      type: "task",
      title: "Reconcile household receipts",
      notes: "Split grocery versus hosting purchases for the budget tracker.",
      status: "in_progress",
      priority: "medium",
      dueAt: at(baseDate, 0, 20, 0),
      category: "Finance",
      tags: ["money", "paperwork"],
      estimatedMinutes: 70,
      energy: "medium",
    },
    {
      id: "property-tax",
      type: "bill",
      title: "Property tax installment",
      notes: "Late fee lands tomorrow morning if this slips again.",
      status: "todo",
      priority: "critical",
      dueAt: at(baseDate, -6, 17, 0),
      category: "Finance",
      tags: ["big bill", "urgent"],
      amount: 610,
      estimatedMinutes: 18,
      energy: "low",
    },
    {
      id: "allergy-refill",
      type: "reminder",
      title: "Refill allergy prescription",
      notes: "Season is peaking, so don't wait until the weekend.",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 5, 9, 30),
      category: "Health",
      tags: ["health", "quick win"],
      estimatedMinutes: 10,
      energy: "low",
    },
    {
      id: "costco-run",
      type: "errand",
      title: "Costco restock run",
      notes: "Paper towels, yogurt tubes, sparkling water, and coffee beans.",
      status: "scheduled",
      priority: "medium",
      dueAt: at(baseDate, 3, 10, 0),
      scheduledAt: at(baseDate, 3, 10, 0),
      category: "Household",
      tags: ["shopping"],
      location: "Costco - North Avenue",
      estimatedMinutes: 80,
      energy: "medium",
    },
    {
      id: "library-books",
      type: "task",
      title: "Return library books",
      status: "done",
      priority: "low",
      dueAt: at(baseDate, -1, 11, 0),
      completedAt: at(baseDate, -1, 10, 30),
      category: "Personal",
      tags: ["done"],
      estimatedMinutes: 10,
      energy: "low",
    },
    {
      id: "streaming-renewal",
      type: "bill",
      title: "Streaming annual renewal",
      status: "paid",
      priority: "low",
      dueAt: at(baseDate, -1, 13, 0),
      completedAt: at(baseDate, -1, 9, 0),
      category: "Subscriptions",
      tags: ["recurring"],
      amount: 79,
      estimatedMinutes: 4,
      energy: "low",
      recurring: true,
    },
    {
      id: "insurance-claim",
      type: "task",
      title: "Call insurance about claim",
      notes: "Have the incident number and repair estimate ready before dialing.",
      status: "todo",
      priority: "critical",
      dueAt: at(baseDate, 0, 11, 30),
      category: "Finance",
      tags: ["phone call", "urgent"],
      estimatedMinutes: 40,
      energy: "high",
    },
    {
      id: "parent-teacher",
      type: "appointment",
      title: "Parent-teacher conference",
      notes: "Bring the reading log and math worksheet notes.",
      status: "scheduled",
      priority: "medium",
      scheduledAt: at(baseDate, 6, 16, 30),
      category: "Family",
      tags: ["school"],
      location: "Westside Elementary",
      estimatedMinutes: 45,
      energy: "medium",
    },
    {
      id: "reply-landlord",
      type: "reminder",
      title: "Reply to landlord email",
      notes: "Just confirm the maintenance window and parking access.",
      status: "snoozed",
      priority: "medium",
      dueAt: at(baseDate, 0, 16, 15),
      category: "Home admin",
      tags: ["email", "quick win"],
      estimatedMinutes: 12,
      energy: "low",
    },
    {
      id: "resume-bullets",
      type: "task",
      title: "Refresh resume bullets",
      notes: "Update the operations examples from the new role.",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 7, 19, 0),
      category: "Career",
      tags: ["career", "future"],
      estimatedMinutes: 55,
      energy: "medium",
    },
    {
      id: "groceries-reset",
      type: "errand",
      title: "Grocery reset for the week",
      notes: "Keep it tight: fruit, sandwich fixings, and breakfast staples.",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, 0, 19, 30),
      category: "Household",
      tags: ["shopping", "today"],
      location: "Marina Market",
      estimatedMinutes: 65,
      energy: "medium",
    },
    {
      id: "childcare-backup",
      type: "task",
      title: "Sort childcare backup plan",
      notes: "Confirm Friday coverage before the travel day gets crowded.",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, 0, 21, 0),
      category: "Family",
      tags: ["planning", "important"],
      estimatedMinutes: 75,
      energy: "high",
    },
  ];
}

export function buildCalmFixture(referenceDate = new Date()): LifeItem[] {
  const baseDate = startOfDay(referenceDate);

  return [
    {
      id: "tea-order",
      type: "errand",
      title: "Pick up tea refill",
      status: "scheduled",
      priority: "medium",
      dueAt: at(baseDate, 1, 11, 0),
      scheduledAt: at(baseDate, 1, 11, 0),
      category: "Personal",
      tags: ["light"],
      location: "Corner Apothecary",
      estimatedMinutes: 20,
      energy: "low",
    },
    {
      id: "friend-birthday",
      type: "reminder",
      title: "Mail birthday card",
      status: "todo",
      priority: "low",
      dueAt: at(baseDate, 2, 15, 0),
      category: "Relationships",
      tags: ["kindness"],
      estimatedMinutes: 12,
      energy: "low",
    },
    {
      id: "yoga-class",
      type: "appointment",
      title: "Evening yoga class",
      status: "scheduled",
      priority: "medium",
      scheduledAt: at(baseDate, 0, 18, 30),
      category: "Wellbeing",
      tags: ["routine"],
      location: "Stillpoint Studio",
      estimatedMinutes: 60,
      energy: "medium",
    },
    {
      id: "water-bill",
      type: "bill",
      title: "Schedule water bill payment",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 4, 16, 0),
      category: "Utilities",
      tags: ["monthly"],
      amount: 44,
      estimatedMinutes: 8,
      energy: "low",
      recurring: true,
    },
  ];
}

export const seedLifeItems = buildSeedLifeItems();
export const calmFixtureItems = buildCalmFixture();
