import { addDays, set, startOfDay, subDays } from "date-fns";

import type {
  ConstraintProfile,
  DashboardWidget,
  Event,
  Gradebook,
  LifeOsSnapshot,
  ProjectMilestone,
  StudyMaterial,
  Task,
  Workspace,
} from "@/lib/life-os/types";

function at(baseDate: Date, dayOffset: number, hour: number, minute = 0) {
  return set(addDays(baseDate, dayOffset), {
    hours: hour,
    minutes: minute,
    seconds: 0,
    milliseconds: 0,
  }).toISOString();
}

function earlier(baseDate: Date, dayOffset: number, hour: number, minute = 0) {
  return set(subDays(baseDate, dayOffset), {
    hours: hour,
    minutes: minute,
    seconds: 0,
    milliseconds: 0,
  }).toISOString();
}

export function buildSeedLifeOsData(referenceDate = new Date()): LifeOsSnapshot {
  const baseDate = startOfDay(referenceDate);

  const workspaces: Workspace[] = [
    {
      id: "course-os",
      name: "Operating Systems",
      shortLabel: "CS 3345",
      kind: "course",
      colorToken: "bg-sky-100 text-sky-950",
      icon: "cpu",
      ownerLabel: "Dr. Nguyen",
      progressSummary: "Scheduler lab and exam prep are shaping the week.",
      active: true,
      creditHours: 3,
      currentGrade: 84,
      targetGrade: 90,
      semesterLabel: "Spring 2026",
    },
    {
      id: "course-linear",
      name: "Linear Algebra",
      shortLabel: "MATH 2418",
      kind: "course",
      colorToken: "bg-amber-100 text-amber-950",
      icon: "sigma",
      ownerLabel: "Prof. Patel",
      progressSummary: "The next problem set still decides the pace.",
      active: true,
      creditHours: 4,
      currentGrade: 91,
      targetGrade: 93,
      semesterLabel: "Spring 2026",
    },
    {
      id: "course-hci",
      name: "Human-Computer Interaction",
      shortLabel: "CS 4389",
      kind: "course",
      colorToken: "bg-emerald-100 text-emerald-950",
      icon: "sparkles",
      ownerLabel: "Dr. Rivera",
      progressSummary: "Prototype critique and reading notes are both live.",
      active: true,
      creditHours: 3,
      currentGrade: 88,
      targetGrade: 92,
      semesterLabel: "Spring 2026",
    },
    {
      id: "course-writing",
      name: "Technical Writing",
      shortLabel: "RHET 3342",
      kind: "course",
      colorToken: "bg-rose-100 text-rose-950",
      icon: "book-open",
      ownerLabel: "Prof. Shah",
      progressSummary: "The proposal draft can still slip if it stays vague.",
      active: true,
      creditHours: 3,
      currentGrade: 86,
      targetGrade: 90,
      semesterLabel: "Spring 2026",
    },
    {
      id: "project-orbit",
      name: "Orbit OS Launch Site",
      shortLabel: "ORBIT",
      kind: "project",
      colorToken: "bg-violet-100 text-violet-950",
      icon: "rocket",
      ownerLabel: "Side build",
      progressSummary: "The landing and motion pass are the next visible shippable slice.",
      active: true,
      projectHealth: "watch",
    },
    {
      id: "project-scout",
      name: "Interview Prep Engine",
      shortLabel: "SCOUT",
      kind: "project",
      colorToken: "bg-cyan-100 text-cyan-950",
      icon: "radar",
      ownerLabel: "Side build",
      progressSummary: "Scheduler logic is ahead of the UI shell.",
      active: true,
      projectHealth: "green",
    },
    {
      id: "project-labs",
      name: "Campus Robotics Demo",
      shortLabel: "ROBOT",
      kind: "project",
      colorToken: "bg-stone-200 text-stone-950",
      icon: "bot",
      ownerLabel: "Team project",
      progressSummary: "The demo script is close, but hardware polish is thin.",
      active: false,
      projectHealth: "risk",
    },
  ];

  const tasks: Task[] = [
    {
      id: "task-os-lab",
      primaryWorkspaceId: "course-os",
      linkedWorkspaceIds: ["project-orbit"],
      kind: "assignment",
      title: "Finish scheduler lab implementation",
      notes: "Wire the ready queue metrics before tomorrow's submission window.",
      status: "in_progress",
      priority: "critical",
      dueAt: at(baseDate, 1, 23, 0),
      tags: ["lab", "systems"],
      estimatedMinutes: 120,
      energy: "high",
    },
    {
      id: "task-os-quiz",
      primaryWorkspaceId: "course-os",
      linkedWorkspaceIds: [],
      kind: "study_session",
      title: "Prep scheduling quiz review set",
      notes: "One fast timed pass plus one correction pass.",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, 2, 10, 0),
      tags: ["quiz", "study"],
      estimatedMinutes: 50,
      energy: "medium",
    },
    {
      id: "task-linear-set",
      primaryWorkspaceId: "course-linear",
      linkedWorkspaceIds: [],
      kind: "assignment",
      title: "Revise eigenvector problem set",
      notes: "Rework questions 4 and 7 before office hours.",
      status: "todo",
      priority: "high",
      dueAt: earlier(baseDate, 1, 18, 0),
      tags: ["math", "problem set"],
      estimatedMinutes: 80,
      energy: "high",
    },
    {
      id: "task-linear-proof",
      primaryWorkspaceId: "course-linear",
      linkedWorkspaceIds: [],
      kind: "study_session",
      title: "Practice diagonalization proof structure",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 3, 19, 0),
      tags: ["proof", "study"],
      estimatedMinutes: 45,
      energy: "medium",
    },
    {
      id: "task-hci-crit",
      primaryWorkspaceId: "course-hci",
      linkedWorkspaceIds: ["project-orbit"],
      kind: "assignment",
      title: "Prepare prototype critique talking points",
      notes: "Two wins, two friction points, one ask for feedback.",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, 0, 20, 30),
      tags: ["prototype", "critique"],
      estimatedMinutes: 40,
      energy: "medium",
    },
    {
      id: "task-hci-reading",
      primaryWorkspaceId: "course-hci",
      linkedWorkspaceIds: [],
      kind: "assignment",
      title: "Annotate inclusive design reading",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 2, 22, 0),
      tags: ["reading"],
      estimatedMinutes: 35,
      energy: "low",
    },
    {
      id: "task-writing-proposal",
      primaryWorkspaceId: "course-writing",
      linkedWorkspaceIds: [],
      kind: "assignment",
      title: "Draft usability memo proposal",
      notes: "Tighten the argument before the workshop block.",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, 1, 17, 0),
      tags: ["writing", "draft"],
      estimatedMinutes: 70,
      energy: "medium",
    },
    {
      id: "task-writing-revision",
      primaryWorkspaceId: "course-writing",
      linkedWorkspaceIds: [],
      kind: "assignment",
      title: "Revise interview summary paragraph",
      status: "todo",
      priority: "medium",
      dueAt: earlier(baseDate, 1, 12, 0),
      tags: ["revision"],
      estimatedMinutes: 25,
      energy: "low",
    },
    {
      id: "task-orbit-shell",
      primaryWorkspaceId: "project-orbit",
      linkedWorkspaceIds: ["course-hci"],
      kind: "project_task",
      title: "Polish Orbit shell interactions",
      notes: "Smooth the page transitions and command receipts.",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, 2, 18, 30),
      tags: ["ui", "motion"],
      estimatedMinutes: 95,
      energy: "high",
    },
    {
      id: "task-scout-model",
      primaryWorkspaceId: "project-scout",
      linkedWorkspaceIds: [],
      kind: "project_task",
      title: "Refine prompt ranking heuristic",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 4, 18, 0),
      tags: ["ranking", "logic"],
      estimatedMinutes: 60,
      energy: "medium",
    },
    {
      id: "task-robot-script",
      primaryWorkspaceId: "project-labs",
      linkedWorkspaceIds: [],
      kind: "project_task",
      title: "Write robotics demo script",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, 3, 15, 0),
      tags: ["demo"],
      estimatedMinutes: 55,
      energy: "medium",
    },
    {
      id: "task-rent",
      primaryWorkspaceId: undefined,
      linkedWorkspaceIds: [],
      kind: "bill",
      title: "Schedule rent payment",
      notes: "Move it today so it clears before the weekend.",
      status: "todo",
      priority: "critical",
      dueAt: earlier(baseDate, 2, 17, 0),
      tags: ["housing", "urgent"],
      amount: 780,
      estimatedMinutes: 10,
      energy: "low",
      recurring: true,
    },
    {
      id: "task-prescription",
      primaryWorkspaceId: undefined,
      linkedWorkspaceIds: [],
      kind: "errand",
      title: "Pick up allergy prescription refill",
      status: "scheduled",
      priority: "medium",
      dueAt: at(baseDate, 0, 14, 15),
      scheduledAt: at(baseDate, 0, 14, 15),
      tags: ["health", "today"],
      location: "Campus Pharmacy",
      estimatedMinutes: 20,
      energy: "low",
    },
    {
      id: "task-groceries",
      primaryWorkspaceId: undefined,
      linkedWorkspaceIds: [],
      kind: "errand",
      title: "Grocery reset for the week",
      status: "todo",
      priority: "medium",
      dueAt: earlier(baseDate, 1, 19, 30),
      tags: ["shopping"],
      location: "Marina Market",
      estimatedMinutes: 50,
      energy: "medium",
    },
  ];

  const events: Event[] = [
    {
      id: "event-os-lecture",
      workspaceId: "course-os",
      kind: "class",
      title: "Operating Systems lecture",
      notes: "CPU scheduling and starvation mitigation.",
      startAt: at(baseDate, 0, 13, 0),
      endAt: at(baseDate, 0, 14, 15),
      location: "ECSS 2.412",
      priority: "high",
      tags: ["lecture"],
    },
    {
      id: "event-linear-office",
      workspaceId: "course-linear",
      kind: "office_hours",
      title: "Linear Algebra office hours",
      startAt: at(baseDate, 0, 15, 30),
      endAt: at(baseDate, 0, 16, 0),
      location: "Green Hall 3.118",
      priority: "medium",
      tags: ["help"],
    },
    {
      id: "event-hci-crit",
      workspaceId: "course-hci",
      kind: "review",
      title: "Prototype critique block",
      startAt: at(baseDate, 2, 18, 0),
      endAt: at(baseDate, 2, 19, 0),
      location: "ATEC 1.208",
      priority: "medium",
      tags: ["critique"],
    },
    {
      id: "event-writing-workshop",
      workspaceId: "course-writing",
      kind: "class",
      title: "Writing workshop",
      startAt: at(baseDate, 1, 11, 0),
      endAt: at(baseDate, 1, 12, 15),
      location: "JO 4.312",
      priority: "medium",
      tags: ["workshop"],
    },
    {
      id: "event-orbit-standup",
      workspaceId: "project-orbit",
      kind: "meeting",
      title: "Orbit design check-in",
      startAt: at(baseDate, 1, 18, 30),
      endAt: at(baseDate, 1, 19, 0),
      location: "Remote",
      priority: "medium",
      tags: ["project"],
    },
    {
      id: "event-robot-demo",
      workspaceId: "project-labs",
      kind: "session",
      title: "Robotics demo dry run",
      startAt: at(baseDate, 4, 16, 0),
      endAt: at(baseDate, 4, 18, 0),
      location: "Innovation Lab",
      priority: "high",
      tags: ["demo"],
    },
  ];

  const materials: StudyMaterial[] = [
    {
      id: "material-os-rubric",
      workspaceId: "course-os",
      kind: "assignment",
      title: "Scheduler lab rubric",
      fileType: "PDF",
      summary: "The rubric is heavy on fairness metrics and clean instrumentation output.",
      addedAt: earlier(baseDate, 1, 10, 0),
      relatedTaskIds: ["task-os-lab"],
    },
    {
      id: "material-os-notes",
      workspaceId: "course-os",
      kind: "notes",
      title: "Lecture notes: CPU scheduling",
      fileType: "Markdown",
      summary: "Round robin versus priority scheduling and the starvation tradeoffs.",
      addedAt: earlier(baseDate, 2, 8, 0),
    },
    {
      id: "material-linear-guide",
      workspaceId: "course-linear",
      kind: "study_guide",
      title: "Eigenvalues review sheet",
      fileType: "PDF",
      summary: "Common proof structures and the most missed matrix setups.",
      addedAt: earlier(baseDate, 3, 11, 0),
      relatedTaskIds: ["task-linear-set"],
    },
    {
      id: "material-hci-spec",
      workspaceId: "course-hci",
      kind: "spec",
      title: "Prototype critique prompt",
      fileType: "PDF",
      summary: "Focus the critique on synthesis quality, evidence, and storytelling confidence.",
      addedAt: earlier(baseDate, 1, 9, 0),
      relatedTaskIds: ["task-hci-crit"],
    },
    {
      id: "material-writing-syllabus",
      workspaceId: "course-writing",
      kind: "syllabus",
      title: "Technical Writing syllabus",
      fileType: "PDF",
      summary: "Workshop cadence, proposal milestones, and memo grading weights.",
      addedAt: earlier(baseDate, 10, 9, 0),
    },
    {
      id: "material-orbit-brief",
      workspaceId: "project-orbit",
      kind: "spec",
      title: "Orbit OS product brief",
      fileType: "Doc",
      summary: "Assistant-centered MVP framing, route map, and home surface goals.",
      addedAt: earlier(baseDate, 1, 14, 0),
      relatedTaskIds: ["task-orbit-shell"],
    },
    {
      id: "material-scout-notes",
      workspaceId: "project-scout",
      kind: "notes",
      title: "Prompt ranking research notes",
      fileType: "Markdown",
      summary: "Early heuristics and examples for choosing the next best study action.",
      addedAt: earlier(baseDate, 4, 18, 0),
      relatedTaskIds: ["task-scout-model"],
    },
  ];

  const milestones: ProjectMilestone[] = [
    {
      id: "milestone-orbit-home",
      workspaceId: "project-orbit",
      title: "Home dashboard polish",
      summary: "Make the assistant-created home surface feel production-ready.",
      dueAt: at(baseDate, 2, 17, 0),
      status: "in_progress",
      progressPercent: 72,
      linkedTaskIds: ["task-orbit-shell"],
    },
    {
      id: "milestone-scout-logic",
      workspaceId: "project-scout",
      title: "Ranking heuristic v1",
      summary: "Lock the next-step prioritization logic before UI expansion.",
      dueAt: at(baseDate, 5, 12, 0),
      status: "planned",
      progressPercent: 38,
      linkedTaskIds: ["task-scout-model"],
    },
    {
      id: "milestone-robot-demo",
      workspaceId: "project-labs",
      title: "Demo run script",
      summary: "Get the story, transitions, and timing ready for the dry run.",
      dueAt: at(baseDate, 4, 14, 0),
      status: "planned",
      progressPercent: 25,
      linkedTaskIds: ["task-robot-script"],
    },
  ];

  const widgets: DashboardWidget[] = [
    {
      id: "widget-primary",
      kind: "primary_recommendation",
      title: "Primary Recommendation",
      description: "What Orbit thinks should move first.",
      href: "/assistant?intent=what_should_i_do_today",
      order: 0,
      accent: "violet",
      layout: "hero",
    },
    {
      id: "widget-summary",
      kind: "assistant_summary",
      title: "Assistant Summary",
      description: "A concise read on today.",
      href: "/assistant",
      order: 1,
      accent: "sky",
      layout: "wide",
    },
    {
      id: "widget-timeline",
      kind: "timeline",
      title: "Timeline",
      description: "The current week in one agenda lens.",
      href: "/calendar",
      order: 2,
      accent: "amber",
      layout: "wide",
    },
    {
      id: "widget-school",
      kind: "school_overview",
      title: "School Overview",
      description: "The strongest academic signals right now.",
      href: "/workspaces?type=course",
      order: 3,
      accent: "emerald",
      layout: "compact",
    },
    {
      id: "widget-projects",
      kind: "active_projects",
      title: "Active Projects",
      description: "What is still shipping on the side.",
      href: "/workspaces?type=project",
      order: 4,
      accent: "violet",
      layout: "compact",
    },
    {
      id: "widget-urgent",
      kind: "urgent_deadlines",
      title: "Urgent Deadlines",
      description: "What could slip first.",
      href: "/assignments?scope=overdue",
      order: 5,
      accent: "rose",
      layout: "compact",
    },
    {
      id: "widget-actions",
      kind: "quick_actions",
      title: "Quick Actions",
      description: "Actions Orbit can take next.",
      href: "/assistant",
      order: 6,
      accent: "sky",
      layout: "compact",
    },
  ];

  const gradebooks: Gradebook[] = [
    {
      workspaceId: "course-os",
      currentGrade: 84,
      targetGrade: 90,
      categories: [
        { id: "os-labs", label: "Labs", weight: 45, currentScore: 86 },
        { id: "os-quizzes", label: "Quizzes", weight: 20, currentScore: 82 },
        { id: "os-final", label: "Final", weight: 35, currentScore: 0 },
      ],
      items: [
        {
          id: "grade-os-lab4",
          workspaceId: "course-os",
          categoryId: "os-labs",
          title: "Scheduler Lab",
          weight: 18,
          maxScore: 100,
          dueAt: at(baseDate, 1, 23, 0),
          status: "planned",
        },
        {
          id: "grade-os-quiz3",
          workspaceId: "course-os",
          categoryId: "os-quizzes",
          title: "Scheduling Quiz",
          weight: 8,
          maxScore: 100,
          score: 82,
          status: "graded",
        },
      ],
    },
    {
      workspaceId: "course-linear",
      currentGrade: 91,
      targetGrade: 93,
      categories: [
        { id: "la-homework", label: "Homework", weight: 35, currentScore: 93 },
        { id: "la-exams", label: "Exams", weight: 45, currentScore: 89 },
        { id: "la-quiz", label: "Quizzes", weight: 20, currentScore: 92 },
      ],
      items: [
        {
          id: "grade-linear-pset",
          workspaceId: "course-linear",
          categoryId: "la-homework",
          title: "Eigenvector Problem Set",
          weight: 12,
          maxScore: 100,
          dueAt: at(baseDate, 1, 18, 0),
          status: "planned",
        },
      ],
    },
    {
      workspaceId: "course-hci",
      currentGrade: 88,
      targetGrade: 92,
      categories: [
        { id: "hci-project", label: "Projects", weight: 55, currentScore: 87 },
        { id: "hci-reading", label: "Readings", weight: 20, currentScore: 92 },
        { id: "hci-final", label: "Final", weight: 25, currentScore: 0 },
      ],
      items: [
        {
          id: "grade-hci-crit",
          workspaceId: "course-hci",
          categoryId: "hci-project",
          title: "Prototype Critique",
          weight: 15,
          maxScore: 100,
          dueAt: at(baseDate, 0, 20, 30),
          status: "planned",
        },
      ],
    },
    {
      workspaceId: "course-writing",
      currentGrade: 86,
      targetGrade: 90,
      categories: [
        { id: "wr-memos", label: "Memos", weight: 40, currentScore: 85 },
        { id: "wr-workshops", label: "Workshops", weight: 20, currentScore: 90 },
        { id: "wr-final", label: "Final Report", weight: 40, currentScore: 0 },
      ],
      items: [
        {
          id: "grade-writing-proposal",
          workspaceId: "course-writing",
          categoryId: "wr-memos",
          title: "Proposal Memo",
          weight: 14,
          maxScore: 100,
          dueAt: at(baseDate, 1, 17, 0),
          status: "planned",
        },
      ],
    },
  ];

  const constraintProfile: ConstraintProfile = {
    weeklyHoursAvailable: 18,
    weeklyBudgetAvailable: 110,
    hoursRemainingThisWeek: 7,
    budgetRemainingThisWeek: 42,
    defaultEnergyProfile: "medium",
  };

  return {
    workspaces,
    tasks,
    events,
    materials,
    milestones,
    widgets,
    gradebooks,
    constraintProfile,
  };
}

export function buildCalmLifeOsData(referenceDate = new Date()): LifeOsSnapshot {
  const baseDate = startOfDay(referenceDate);

  const workspaces: Workspace[] = [
    {
      id: "course-calm",
      name: "Interaction Design",
      shortLabel: "DES 3301",
      kind: "course",
      colorToken: "bg-sky-100 text-sky-950",
      icon: "sparkles",
      ownerLabel: "Prof. Lee",
      progressSummary: "Only light upkeep remains.",
      active: true,
      creditHours: 3,
      currentGrade: 93,
      targetGrade: 93,
    },
    {
      id: "project-calm",
      name: "Reading Notes Archive",
      shortLabel: "ARCH",
      kind: "project",
      colorToken: "bg-stone-200 text-stone-950",
      icon: "folder-open",
      ownerLabel: "Personal project",
      progressSummary: "This board is stable.",
      active: true,
      projectHealth: "green",
    },
  ];

  const tasks: Task[] = [
    {
      id: "quiet-reading",
      primaryWorkspaceId: "course-calm",
      linkedWorkspaceIds: [],
      kind: "study_session",
      title: "Read one portfolio case study",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 2, 18, 0),
      tags: ["reading"],
      estimatedMinutes: 30,
      energy: "low",
    },
    {
      id: "tea-refill",
      primaryWorkspaceId: undefined,
      linkedWorkspaceIds: [],
      kind: "errand",
      title: "Pick up tea refill",
      status: "scheduled",
      priority: "low",
      dueAt: at(baseDate, 1, 11, 0),
      scheduledAt: at(baseDate, 1, 11, 0),
      tags: ["errand"],
      location: "Corner Apothecary",
      estimatedMinutes: 20,
      energy: "low",
    },
  ];

  const events: Event[] = [
    {
      id: "quiet-session",
      workspaceId: "course-calm",
      kind: "session",
      title: "Light study block",
      startAt: at(baseDate, 0, 18, 30),
      endAt: at(baseDate, 0, 19, 15),
      priority: "low",
      tags: ["light"],
    },
  ];

  const materials: StudyMaterial[] = [
    {
      id: "quiet-guide",
      workspaceId: "course-calm",
      kind: "study_guide",
      title: "Reading guide",
      fileType: "PDF",
      summary: "A short guide to keep the session focused.",
      addedAt: earlier(baseDate, 1, 10, 0),
    },
  ];

  return {
    workspaces,
    tasks,
    events,
    materials,
    milestones: [
      {
        id: "calm-milestone",
        workspaceId: "project-calm",
        title: "Archive cleanup",
        summary: "This milestone is paced and non-urgent.",
        dueAt: at(baseDate, 7, 18, 0),
        status: "planned",
        progressPercent: 40,
      },
    ],
    widgets: [
      {
        id: "quiet-primary",
        kind: "primary_recommendation",
        title: "Primary Recommendation",
        description: "A calm next move.",
        href: "/assistant?intent=what_should_i_do_today",
        order: 0,
        accent: "violet",
        layout: "hero",
      },
    ],
    gradebooks: [
      {
        workspaceId: "course-calm",
        currentGrade: 93,
        targetGrade: 93,
        categories: [{ id: "c1", label: "Studio", weight: 100, currentScore: 93 }],
        items: [],
      },
    ],
    constraintProfile: {
      weeklyHoursAvailable: 10,
      weeklyBudgetAvailable: 60,
      hoursRemainingThisWeek: 5,
      budgetRemainingThisWeek: 48,
      defaultEnergyProfile: "low",
    },
  };
}

export const seedLifeOsData = buildSeedLifeOsData();
