import { addDays, set, startOfDay, subDays } from "date-fns";

import type {
  ConstraintProfile,
  Event,
  Gradebook,
  LifeOsSnapshot,
  ProgressRecord,
  StudyMaterial,
  Task,
  Workspace,
} from "@/lib/life-os/types";

function at(baseDate: Date, dayOffset: number, hour: number, minute = 0) {
  return set(addDays(baseDate, dayOffset), {
    hours: hour,
    minutes: minute,
    seconds: 0,
    milliseconds: 0,
  }).toISOString();
}

function earlier(baseDate: Date, dayOffset: number, hour: number, minute = 0) {
  return set(subDays(baseDate, dayOffset), {
    hours: hour,
    minutes: minute,
    seconds: 0,
    milliseconds: 0,
  }).toISOString();
}

export function buildSeedLifeOsData(referenceDate = new Date()): LifeOsSnapshot {
  const baseDate = startOfDay(referenceDate);

  const workspaces: Workspace[] = [
    {
      id: "course-os",
      name: "Operating Systems",
      shortLabel: "CS 3345",
      kind: "course",
      colorToken: "bg-sky-100 text-sky-900",
      icon: "cpu",
      ownerLabel: "Dr. Nguyen",
      progressSummary: "Two graded items still move the semester.",
      creditHours: 3,
      currentGrade: 75,
      targetGrade: 87,
    },
    {
      id: "course-linear",
      name: "Linear Algebra",
      shortLabel: "MATH 2418",
      kind: "course",
      colorToken: "bg-amber-100 text-amber-900",
      icon: "sigma",
      ownerLabel: "Prof. Patel",
      progressSummary: "Holding steady, but the next problem set matters.",
      creditHours: 4,
      currentGrade: 89,
      targetGrade: 90,
    },
    {
      id: "study-ux",
      name: "UX Research Certificate",
      shortLabel: "UXR",
      kind: "study_track",
      colorToken: "bg-emerald-100 text-emerald-900",
      icon: "compass",
      ownerLabel: "Self-paced cohort",
      progressSummary: "Module 4 is open and the critique window is near.",
    },
    {
      id: "study-spanish",
      name: "Spanish B1 Sprint",
      shortLabel: "SPAN B1",
      kind: "study_track",
      colorToken: "bg-rose-100 text-rose-900",
      icon: "languages",
      ownerLabel: "Evening practice block",
      progressSummary: "Conversation confidence is lagging behind reading.",
    },
    {
      id: "admin-life",
      name: "Personal Admin",
      shortLabel: "ADMIN",
      kind: "admin",
      colorToken: "bg-stone-200 text-stone-900",
      icon: "wallet",
      ownerLabel: "Life flows",
      progressSummary: "Bills and paperwork can still crowd the week.",
    },
    {
      id: "personal-wellbeing",
      name: "Personal Wellbeing",
      shortLabel: "LIFE",
      kind: "personal",
      colorToken: "bg-lime-100 text-lime-900",
      icon: "heart",
      ownerLabel: "Daily upkeep",
      progressSummary: "Errands are manageable if they stay clustered.",
    },
    {
      id: "work-campus",
      name: "Campus Makerspace",
      shortLabel: "WORK",
      kind: "work",
      colorToken: "bg-violet-100 text-violet-900",
      icon: "briefcase",
      ownerLabel: "Lab supervisor",
      progressSummary: "One shift checklist and one follow-up are still open.",
    },
  ];

  const tasks: Task[] = [
    {
      id: "task-rent",
      workspaceId: "admin-life",
      kind: "bill",
      title: "Schedule rent payment",
      notes: "Move it today so it clears before the weekend.",
      status: "todo",
      priority: "critical",
      dueAt: earlier(baseDate, 2, 17, 0),
      tags: ["housing", "urgent"],
      amount: 780,
      estimatedMinutes: 10,
      energy: "low",
      recurring: true,
    },
    {
      id: "task-claim",
      workspaceId: "admin-life",
      kind: "admin",
      title: "Upload insurance claim receipts",
      notes: "Submit the repair estimate before the case auto-closes.",
      status: "todo",
      priority: "high",
      dueAt: earlier(baseDate, 1, 11, 30),
      tags: ["paperwork", "deadline"],
      estimatedMinutes: 35,
      energy: "medium",
    },
    {
      id: "task-grocery",
      workspaceId: "personal-wellbeing",
      kind: "errand",
      title: "Grocery reset for the week",
      notes: "Keep it tight: fruit, yogurt, sandwich fixings, and coffee.",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 0, 19, 30),
      tags: ["shopping", "home"],
      location: "Marina Market",
      estimatedMinutes: 55,
      energy: "medium",
    },
    {
      id: "task-os-lab",
      workspaceId: "course-os",
      kind: "assignment",
      title: "Finish scheduler lab implementation",
      notes: "Wire the ready queue metrics before tomorrow's submission window.",
      status: "in_progress",
      priority: "critical",
      dueAt: at(baseDate, 1, 23, 0),
      tags: ["lab", "systems"],
      estimatedMinutes: 120,
      energy: "high",
    },
    {
      id: "task-os-outline",
      workspaceId: "course-os",
      kind: "assignment",
      title: "Draft kernel reading response",
      notes: "Turn the margin notes into a clean one-page argument.",
      status: "todo",
      priority: "high",
      dueAt: earlier(baseDate, 1, 17, 30),
      tags: ["reading", "essay"],
      estimatedMinutes: 45,
      energy: "medium",
    },
    {
      id: "task-linear-set",
      workspaceId: "course-linear",
      kind: "assignment",
      title: "Revise eigenvector problem set",
      notes: "Rework questions 4 and 7 before office hours.",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, 1, 18, 0),
      tags: ["math", "problem set"],
      estimatedMinutes: 70,
      energy: "high",
    },
    {
      id: "task-linear-quiz",
      workspaceId: "course-linear",
      kind: "study_session",
      title: "Practice determinant quiz set",
      notes: "Aim for one clean timed pass tonight.",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 2, 20, 0),
      tags: ["quiz prep"],
      estimatedMinutes: 50,
      energy: "medium",
    },
    {
      id: "task-ux-module",
      workspaceId: "study-ux",
      kind: "study_session",
      title: "Complete module 4 interview synthesis",
      notes: "Turn the raw notes into three usable research themes.",
      status: "todo",
      priority: "high",
      dueAt: at(baseDate, 2, 21, 0),
      tags: ["certificate", "research"],
      estimatedMinutes: 80,
      energy: "high",
    },
    {
      id: "task-ux-critique",
      workspaceId: "study-ux",
      kind: "assignment",
      title: "Prepare portfolio critique talking points",
      notes: "Two wins, two friction points, one ask for feedback.",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 0, 20, 30),
      tags: ["portfolio", "feedback"],
      estimatedMinutes: 40,
      energy: "medium",
    },
    {
      id: "task-spanish-speaking",
      workspaceId: "study-spanish",
      kind: "study_session",
      title: "Record 20-minute speaking drill",
      notes: "Use the restaurant scenario prompts from the tutor notes.",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 1, 19, 0),
      tags: ["speaking", "practice"],
      estimatedMinutes: 25,
      energy: "medium",
    },
    {
      id: "task-spanish-review",
      workspaceId: "study-spanish",
      kind: "study_session",
      title: "Review B1 verb tense flashcards",
      notes: "Short pass only. The goal is consistency, not a marathon.",
      status: "todo",
      priority: "low",
      dueAt: at(baseDate, 0, 21, 0),
      tags: ["flashcards", "quick win"],
      estimatedMinutes: 18,
      energy: "low",
    },
    {
      id: "task-work-checklist",
      workspaceId: "work-campus",
      kind: "work_task",
      title: "Prep Friday lab shift checklist",
      notes: "Flag the 3D printer maintenance steps and new student safety notes.",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 1, 13, 30),
      tags: ["shift", "ops"],
      estimatedMinutes: 35,
      energy: "medium",
    },
    {
      id: "task-work-followup",
      workspaceId: "work-campus",
      kind: "work_task",
      title: "Send internship follow-up email",
      notes: "Thank them for the tour and attach the revised availability note.",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 0, 16, 0),
      tags: ["career", "email"],
      estimatedMinutes: 20,
      energy: "low",
    },
    {
      id: "task-wellbeing-refill",
      workspaceId: "personal-wellbeing",
      kind: "errand",
      title: "Pick up allergy prescription refill",
      notes: "Bring the new insurance card.",
      status: "scheduled",
      priority: "medium",
      dueAt: at(baseDate, 0, 14, 15),
      scheduledAt: at(baseDate, 0, 14, 15),
      tags: ["health", "today"],
      location: "Campus Pharmacy",
      estimatedMinutes: 20,
      energy: "low",
    },
    {
      id: "task-admin-budget",
      workspaceId: "admin-life",
      kind: "admin",
      title: "Trim this week's discretionary spending",
      notes: "Dining-out is the easiest line to compress if the budget stays tight.",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 3, 18, 0),
      tags: ["budget", "planning"],
      estimatedMinutes: 30,
      energy: "medium",
    },
  ];

  const events: Event[] = [
    {
      id: "event-os-lecture",
      workspaceId: "course-os",
      kind: "class",
      title: "Operating Systems lecture",
      notes: "CPU scheduling and starvation mitigation.",
      startAt: at(baseDate, 0, 13, 0),
      endAt: at(baseDate, 0, 14, 15),
      location: "ECSS 2.412",
      priority: "high",
      tags: ["lecture"],
    },
    {
      id: "event-linear-office-hours",
      workspaceId: "course-linear",
      kind: "office_hours",
      title: "Linear Algebra office hours",
      notes: "Bring question 7 and the diagonalization proof attempt.",
      startAt: at(baseDate, 0, 15, 30),
      endAt: at(baseDate, 0, 16, 0),
      location: "Green Hall 3.118",
      priority: "medium",
      tags: ["help", "math"],
    },
    {
      id: "event-ux-critique",
      workspaceId: "study-ux",
      kind: "review",
      title: "Peer portfolio critique",
      notes: "Async cohort review window.",
      startAt: at(baseDate, 2, 18, 0),
      endAt: at(baseDate, 2, 19, 0),
      location: "Remote",
      priority: "medium",
      tags: ["cohort", "feedback"],
    },
    {
      id: "event-spanish-call",
      workspaceId: "study-spanish",
      kind: "session",
      title: "Conversation exchange call",
      notes: "Aim for food, travel, and work stories only.",
      startAt: at(baseDate, 1, 19, 30),
      endAt: at(baseDate, 1, 20, 0),
      location: "Remote",
      priority: "medium",
      tags: ["speaking"],
    },
    {
      id: "event-dentist",
      workspaceId: "personal-wellbeing",
      kind: "appointment",
      title: "Dental cleaning",
      notes: "Bring the updated insurance card.",
      startAt: at(baseDate, 4, 9, 0),
      endAt: at(baseDate, 4, 10, 0),
      location: "North Loop Dental",
      priority: "low",
      tags: ["health"],
    },
    {
      id: "event-work-shift",
      workspaceId: "work-campus",
      kind: "session",
      title: "Makerspace shift",
      notes: "Cover the laser cutter intake and printer queue.",
      startAt: at(baseDate, 1, 16, 0),
      endAt: at(baseDate, 1, 20, 0),
      location: "Makerspace",
      priority: "medium",
      tags: ["shift"],
    },
  ];

  const materials: StudyMaterial[] = [
    {
      id: "material-os-rubric",
      workspaceId: "course-os",
      kind: "assignment",
      title: "Scheduler lab rubric",
      fileType: "PDF",
      summary: "The rubric is heavy on fairness metrics and clean instrumentation output.",
      addedAt: earlier(baseDate, 1, 10, 0),
      relatedTaskIds: ["task-os-lab"],
    },
    {
      id: "material-os-notes",
      workspaceId: "course-os",
      kind: "notes",
      title: "Lecture notes: CPU scheduling",
      fileType: "Markdown",
      summary: "Round robin versus priority scheduling and the starvation tradeoffs.",
      addedAt: earlier(baseDate, 2, 8, 0),
    },
    {
      id: "material-linear-guide",
      workspaceId: "course-linear",
      kind: "study_guide",
      title: "Eigenvalues review sheet",
      fileType: "PDF",
      summary: "The sheet clusters common proof structures and the most missed matrix setups.",
      addedAt: earlier(baseDate, 3, 11, 0),
      relatedTaskIds: ["task-linear-set", "task-linear-quiz"],
    },
    {
      id: "material-ux-spec",
      workspaceId: "study-ux",
      kind: "spec",
      title: "Module 4 critique prompt",
      fileType: "PDF",
      summary: "Focus the critique on synthesis quality, evidence, and storytelling confidence.",
      addedAt: earlier(baseDate, 1, 9, 0),
      relatedTaskIds: ["task-ux-module", "task-ux-critique"],
    },
    {
      id: "material-spanish-notes",
      workspaceId: "study-spanish",
      kind: "notes",
      title: "Tutor notes: B1 conversation drills",
      fileType: "Doc",
      summary: "Best gains will come from spontaneous responses rather than more reading.",
      addedAt: earlier(baseDate, 1, 19, 0),
      relatedTaskIds: ["task-spanish-speaking", "task-spanish-review"],
    },
  ];

  const gradebooks: Gradebook[] = [
    {
      workspaceId: "course-os",
      currentGrade: 75,
      targetGrade: 87,
      categories: [
        { id: "os-labs", label: "Labs", weight: 45, currentScore: 79 },
        { id: "os-quizzes", label: "Quizzes", weight: 20, currentScore: 86 },
        { id: "os-final", label: "Final", weight: 35, currentScore: 0 },
      ],
      items: [
        {
          id: "grade-os-lab4",
          workspaceId: "course-os",
          categoryId: "os-labs",
          title: "Scheduler Lab",
          weight: 18,
          maxScore: 100,
          dueAt: at(baseDate, 1, 23, 0),
          status: "planned",
        },
        {
          id: "grade-os-quiz3",
          workspaceId: "course-os",
          categoryId: "os-quizzes",
          title: "Scheduling Quiz",
          weight: 8,
          maxScore: 100,
          score: 86,
          status: "graded",
        },
      ],
    },
    {
      workspaceId: "course-linear",
      currentGrade: 89,
      targetGrade: 90,
      categories: [
        { id: "la-homework", label: "Homework", weight: 35, currentScore: 91 },
        { id: "la-exams", label: "Exams", weight: 45, currentScore: 87 },
        { id: "la-quiz", label: "Quizzes", weight: 20, currentScore: 90 },
      ],
      items: [
        {
          id: "grade-linear-pset",
          workspaceId: "course-linear",
          categoryId: "la-homework",
          title: "Eigenvector Problem Set",
          weight: 12,
          maxScore: 100,
          dueAt: at(baseDate, 1, 18, 0),
          status: "planned",
        },
        {
          id: "grade-linear-midterm",
          workspaceId: "course-linear",
          categoryId: "la-exams",
          title: "Midterm",
          weight: 20,
          maxScore: 100,
          score: 88,
          status: "graded",
        },
      ],
    },
  ];

  const progressRecords: ProgressRecord[] = [
    {
      id: "progress-ux-modules",
      workspaceId: "study-ux",
      label: "Modules completed",
      currentValue: 3,
      targetValue: 5,
      unit: "modules",
      confidence: "medium",
      dueAt: at(baseDate, 9, 18, 0),
    },
    {
      id: "progress-ux-critiques",
      workspaceId: "study-ux",
      label: "Portfolio critiques",
      currentValue: 1,
      targetValue: 3,
      unit: "reviews",
      confidence: "medium",
      dueAt: at(baseDate, 7, 18, 0),
    },
    {
      id: "progress-spanish-speaking",
      workspaceId: "study-spanish",
      label: "Speaking sessions",
      currentValue: 2,
      targetValue: 4,
      unit: "sessions",
      confidence: "low",
      dueAt: at(baseDate, 6, 20, 0),
    },
  ];

  const constraintProfile: ConstraintProfile = {
    weeklyHoursAvailable: 16,
    weeklyBudgetAvailable: 95,
    hoursRemainingThisWeek: 6,
    budgetRemainingThisWeek: 34,
    defaultEnergyProfile: "medium",
  };

  return {
    workspaces,
    tasks,
    events,
    materials,
    gradebooks,
    progressRecords,
    constraintProfile,
  };
}

export function buildCalmLifeOsData(referenceDate = new Date()): LifeOsSnapshot {
  const baseDate = startOfDay(referenceDate);

  const workspaces: Workspace[] = [
    {
      id: "study-quiet",
      name: "Portfolio Reading Sprint",
      shortLabel: "READ",
      kind: "study_track",
      colorToken: "bg-sky-100 text-sky-900",
      icon: "book-open",
      ownerLabel: "Self-paced",
      progressSummary: "Steady momentum with no immediate risk.",
    },
    {
      id: "personal-light",
      name: "Personal Wellbeing",
      shortLabel: "LIFE",
      kind: "personal",
      colorToken: "bg-lime-100 text-lime-900",
      icon: "heart",
      ownerLabel: "Daily upkeep",
      progressSummary: "Only light upkeep is left on the board.",
    },
  ];

  const tasks: Task[] = [
    {
      id: "quiet-reading",
      workspaceId: "study-quiet",
      kind: "study_session",
      title: "Read one portfolio case study",
      status: "todo",
      priority: "medium",
      dueAt: at(baseDate, 2, 18, 0),
      tags: ["reading"],
      estimatedMinutes: 30,
      energy: "low",
    },
    {
      id: "tea-refill",
      workspaceId: "personal-light",
      kind: "errand",
      title: "Pick up tea refill",
      status: "scheduled",
      priority: "low",
      dueAt: at(baseDate, 1, 11, 0),
      scheduledAt: at(baseDate, 1, 11, 0),
      tags: ["errand"],
      location: "Corner Apothecary",
      estimatedMinutes: 20,
      energy: "low",
    },
  ];

  const events: Event[] = [
    {
      id: "quiet-session",
      workspaceId: "study-quiet",
      kind: "session",
      title: "Light study block",
      startAt: at(baseDate, 0, 18, 30),
      endAt: at(baseDate, 0, 19, 15),
      priority: "low",
      tags: ["light"],
    },
  ];

  const materials: StudyMaterial[] = [
    {
      id: "quiet-guide",
      workspaceId: "study-quiet",
      kind: "study_guide",
      title: "Reading guide",
      fileType: "PDF",
      summary: "A short guide to keep the session focused.",
      addedAt: earlier(baseDate, 1, 10, 0),
    },
  ];

  const constraintProfile: ConstraintProfile = {
    weeklyHoursAvailable: 10,
    weeklyBudgetAvailable: 60,
    hoursRemainingThisWeek: 5,
    budgetRemainingThisWeek: 48,
    defaultEnergyProfile: "low",
  };

  return {
    workspaces,
    tasks,
    events,
    materials,
    gradebooks: [],
    progressRecords: [
      {
        id: "quiet-progress",
        workspaceId: "study-quiet",
        label: "Sessions completed",
        currentValue: 2,
        targetValue: 4,
        unit: "sessions",
        confidence: "medium",
      },
    ],
    constraintProfile,
  };
}

export const seedLifeOsData = buildSeedLifeOsData();
